version: "3"

services:
  nginx:
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file: 
      - .env
    image: nginx
    container_name: nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    restart: always

  wordpress:
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    env_file:
      - .env
    restart: always
    expose:
      - "9000"

  mariadb:
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb
    container_name: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    env_file:
      - .env
    restart: on-failure
    expose:
      - "3306"


networks:
  inception:
    driver: bridge

volumes:
  wordpress:
    driver: local
    driver_opts:
      device: /home/mhadi/data/wordpress
      o: bind
      type: none
  mariadb:
    driver: local
    driver_opts:
      device: /home/mhadi/data/mariadb
      o: bind
      type: none